# Events may have types to be more specific about when to trigger
name: Workflow 004
on:
  issues:
    types:
      - opened
      - edited
jobs:
  job_001:
    runs-on: ubuntu-latest
    steps:
      - run: ""