name: Workflow trufflehog
on:
  workflow_dispatch:
jobs:
  job_001:
    runs-on: ubuntu-latest
    steps:
      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: .
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
