name: Workflow 009
on:
  issues:
    types:
      - edited
jobs:
  job_001:
    runs-on: ubuntu-latest
    steps:
      - run: echo "you can use expressions using dollar + mustache notation"
      - run: echo "${{ !true }}"
      - run: echo "your workflow receive some variables with information that you may need"
      - run: echo "${{ runner.os }}"
      - run: echo "${{ github.event_name }}"
      - run: echo "${{ github.ref }}"
      - run: echo "${{ github.repository }}"
      - run: echo "${{ github.workspace }}"
      - run: echo "${{ job.status }}"
