name: Workflow 008
on:
  workflow_dispatch:
jobs:
  job_001:
    runs-on: ubuntu-latest
    steps:
      - run: echo "actions can receive parameters to work with through th key 'with'"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.1'
      - run: python --version
