name: Workflow 012
on:
  issues:
    types:
      - edited
jobs:
  job_001:
    runs-on: ubuntu-latest
    steps:
      - run: echo "IF it's the safe way to evaluate expressions"
      - run: export TEST=true
      - run: echo "yes!"
        if: $TEST == "true"
