name: Workflow 007
on:
  issues:
    types:
      - edited
jobs:
  job_001:
    runs-on: ubuntu-latest
    steps:
      - run: echo "there is two types of steps"
      - run: echo "run - the basic step of executing something in terminal"
      - run: echo "uses - reusing steps made by someone (also know as actions)"
      - uses: actions/checkout@v3
      - run: echo "the previous action will `git checkout` to your repository"
