name: Workflow 014
on:
  workflow_dispatch:
jobs:
  job_001:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
      
      - run: git status
      - run: echo 'hello' > example.txt
      - run: git status
          
      - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - run: git config --global user.name "github-actions"
      - run: git add -A
      - run: git commit -m "Test"
      - run: git push