name: Workflow 012
on:
  workflow_dispatch:
jobs:
  job_001:
    runs-on: ubuntu-latest
    steps:
      - run: echo "github gives you functions to hepl in mustache operations"
      - run: echo "${{ contains('hello friend', 'hello') }}"
      - run: echo "${{ contains('hello friend', 'he') }}"
      - run: echo "${{ contains('hello friend', 'he ') }}"
      - run: echo "${{ contains(['hello', 'friend'], 'hello') }}"
      - run: echo "${{ contains(['he', 'friend'], 'hello') }}"
