name: Workflow 014
on:
  workflow_dispatch:
jobs:
  job_001:
    runs-on: ubuntu-latest
    outputs:
      out1: ${{ steps.step1.outputs.hello}}
    steps:
      - id: step1
        run: echo "hello=world" >> $GITHUB_OUTPUT
      - id: step2
        run: echo ${{ step.step1.outputs.out1 }}
