name: Workflow 005
on:
  workflow_dispatch:
jobs:
  job_001:
    runs-on: ubuntu-latest
    steps:
      - run: echo "run command is the more basic command you can have"
      - run: echo "it will execute commands like you would be doing in the terminal"
      - run: echo "if one step fail, this job will stop"
