name: Workflow 014
on:
  workflow_dispatch:
jobs:
  job_001:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
      
      - run: git status
      - run: echo 'hello' > example.txt
      - run: git status
          
      - run: git config -l

      - uses: EndBug/add-and-commit@v9
        with:
          message: Test
          default_author: github_actions
          push: false
          
      - run: git config -l
      - run: git push